In [1]:
import pandas as pd 
import numpy as np
import matplotlib as plt
import seaborn as sns

In [3]:
### Catagorical Data 
# type of catagorical data 
# nominal data this has no order or relation e.g classes 
# Ordinal data has relationship with each other e.g post of officers

In [4]:
## Catagorical Data encoding type
# Ordinal encoding, label encoding
# one hot en-coding

In [5]:
# out columns is catagorical like classification then we use label encoding
# ordinal encoding is used in input catgorical columns

In [104]:
df = pd.read_csv('customer.csv')
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [105]:
df =df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [96]:
from sklearn.model_selection import train_test_split

In [106]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [107]:
from sklearn.preprocessing import OrdinalEncoder

In [108]:
X_train.head()

review education
44  Average        UG
19     Poor        PG
41     Good        PG
27     Poor        PG
31     Poor    School

In [109]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [110]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [111]:
X_train = oe.transform(X_train)

In [116]:
X_train[1]

array([0., 2.])

In [117]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [118]:
from sklearn.preprocessing import LabelEncoder

In [119]:
le = LabelEncoder()  ## its used target values

In [120]:
le.fit(y_train)

LabelEncoder()

In [121]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [122]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [123]:
y_train

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1])

In [124]:
y_test

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 1])